[pytest]
dotenv_file = .env
addopts = --headed

# Browser configurations
playwright_browser = chromium
playwright_headed = True
playwright_timeout = 10000
playwright_viewport_width = 1980
playwright_viewport_height = 1080